version: '3.9'

services:
  api:
    build: .
    container_name: competence-api
    ports:
      - '8000:8000'
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - mongo

  frontend:
    build:
      context: ../frontend
    container_name: competence-frontend
    ports:
      - '5173:80'
    depends_on:
      - api

  mongo:
    image: mongo:6
    container_name: mongo-db
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
